---
services:
  wb:
    build:
      context: .
      dockerfile: Dockerfile
    # No need for ports or volumes here for just building
    # command: python -m waveload # Your application command

  #coverage_export:
  ce:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
